version: '3'
services:
  single_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0-SNAPSHOT
    container_name: single_node
    restart: always
    networks: 
      - elastic
    volumes:
      - /home/eason/elasticsearch_proj/cluster/data/single_node:/usr/share/elasticsearch/data
      - /home/eason/elasticsearch_proj/cluster/config/single_node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/eason/elasticsearch_proj/cluster/log/single_node:/usr/share/elasticsearch/logs
      # - /home/eason/elasticsearch_proj/cluster/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    ports:
      - 9200:9200/tcp
    deploy:
      resources:
        limits:
          cpus: '4.00'

networks:
  elastic: 
