version: '3'
services:
  single_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0-SNAPSHOT
    # stdin_open: true
    # tty: true
    # entrypoint: ["bash"]
    container_name: single_node
    restart: always
    networks: 
      - elastic
    volumes:
      - /home/eason/elasticsearch_proj/elasticsearch/build/distribution/local/elasticsearch-8.9.0-SNAPSHOT:/usr/share/elasticsearch
      - /home/eason/elasticsearch_proj/autocancel_exp/elasticsearch_exp/cluster/data/single_node:/usr/share/elasticsearch/data
      - /home/eason/elasticsearch_proj/autocancel_exp/elasticsearch_exp/cluster/config/single_node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/eason/elasticsearch_proj/autocancel_exp/elasticsearch_exp/cluster/config/java.policy:/usr/share/elasticsearch/config/java.policy
      - /home/eason/elasticsearch_proj/autocancel_exp/elasticsearch_exp/cluster/log/single_node:/usr/share/elasticsearch/logs
      - /home/eason/elasticsearch_proj/autocancel_exp/elasticsearch_exp/cluster/log/cancel_info/$CASE_$START_TIME:/tmp/autocancel
      # - /home/eason/elasticsearch_proj/autocancel_exp/elasticsearch_exp/cluster/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g -ea:org.elasticsearch.autocancel... -Djava.security.policy=/usr/share/elasticsearch/config/java.policy -Ddefault.policy=$DEFAULT_POLICY -Dpredict.progress=$PREDICT_PROGRESS -Dexperiment.mode=$EXPERIMENT_MODE -XX:InitiatingHeapOccupancyPercent=10 -agentpath:/usr/share/elasticsearch/data/liblagent.so"
    ports:
      - 9200:9200/tcp
    deploy:
      resources:
        limits:
          cpus: '8.00'
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '12mb'

networks:
  elastic: 
