version: '3'
services:
  single_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0-SNAPSHOT
    # stdin_open: true
    # tty: true
    # entrypoint: ["bash"]
    container_name: single_node
    restart: always
    networks: 
      - elastic
    volumes:
      - $AUTOCANCEL_HOME/elasticsearch/build/distribution/local/elasticsearch-8.9.0-SNAPSHOT:/usr/share/elasticsearch
      - $AUTOCANCEL_HOME/autocancel_exp/elasticsearch_exp/cluster/data/single_node:/usr/share/elasticsearch/data
      - $AUTOCANCEL_HOME/autocancel_exp/elasticsearch_exp/cluster/config/single_node.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - $AUTOCANCEL_HOME/autocancel_exp/elasticsearch_exp/cluster/config/java.policy:/usr/share/elasticsearch/config/java.policy
      - $AUTOCANCEL_HOME/autocancel_exp/elasticsearch_exp/cluster/log/single_node:/usr/share/elasticsearch/logs
      - $AUTOCANCEL_HOME/autocancel_exp/elasticsearch_exp/cluster/log/cancel_info/${CASE}_${START_TIME}:/tmp/autocancel
      # - $AUTOCANCEL_HOME/autocancel_exp/elasticsearch_exp/cluster/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g -ea:autocancel... -Djava.security.policy=/usr/share/elasticsearch/config/java.policy -Ddefault.policy=$DEFAULT_POLICY -Dpredict.progress=$PREDICT_PROGRESS -Dcancel.enable=$CANCEL_ENABLE -Dautocancel.log=$AUTOCANCEL_LOG -XX:InitiatingHeapOccupancyPercent=10"
    ports:
      - 9200:9200/tcp
    deploy:
      resources:
        limits:
          cpus: '8.00'
    user: "$USER_ID:$GROUP_ID"
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '12mb'

networks:
  elastic: 
